---
name: Call Trivy
on:
  push:
    branches: [main]
  pull_request:
jobs:
  scan:
    name: Scan
    uses: sloths-of-yore/actions/.github/workflows/reusable-trivy.yml@main
    with:
      image-name: 'ghcr.io/sloths-of-yore/wordsmith-web'
      image-tag: gha-${{ github.run_id }}
